# Generated by Django 4.2.3 on 2023-07-07 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('user_name', models.CharField(max_length=30)),
                ('user_mail_id', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='PostsCollection',
            fields=[
                ('post_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('post_category', models.CharField(max_length=50)),
                ('post_text', models.CharField(max_length=500)),
                ('post_img', models.ImageField(upload_to='pics')),
                ('post_caption', models.CharField(max_length=500)),
                ('like_fk', models.IntegerField()),
                ('comment_fk', models.CharField(max_length=500)),
                ('date_posted', models.DateTimeField()),
                ('date_last_modified', models.DateTimeField()),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='forum_post.users')),
            ],
        ),
    ]
