# Generated by Django 4.2 on 2023-07-04 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=500)),
                ('image', models.CharField(max_length=500)),
                ('categories', models.CharField(max_length=50)),
                ('like', models.IntegerField()),
                ('comment', models.CharField(max_length=500)),
                ('caption', models.CharField(max_length=500)),
                ('createdat', models.IntegerField()),
                ('createddate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('createdat', models.IntegerField()),
                ('createddate', models.DateTimeField()),
            ],
        ),
    ]
